# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        registry: private.docker.xenit.eu
        username: ${{ secrets.CLOUDSMITH_USER }}
        password: ${{ secrets.CLOUDSMITH_APIKEY }}
    - name: Publish docker image
      if: ${{ startsWith(github.ref, 'refs/heads/master') }}
      uses: gradle/gradle-build-action@v2.3.3
      env:
        BRANCH_NAME: ${{ github.ref_name }}
      with:
        arguments: pushDockerImage